// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatIs1CFramework.Data;

namespace WhatIs1CFramework.Migrations
{
    [DbContext(typeof(WhatIs1CFrameworkContext))]
    partial class WhatIs1CFrameworkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0-preview1.19506.2");

            modelBuilder.Entity("WhatIs1CFramework.Models.Article", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("WhatIs1CFramework.Models.Picture", b =>
                {
                    b.Property<int>("PictureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleID")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImageByte")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("PictureID");

                    b.HasIndex("ArticleID");

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("WhatIs1CFramework.Models.Picture", b =>
                {
                    b.HasOne("WhatIs1CFramework.Models.Article", "Article")
                        .WithMany("Pictures")
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
